#ifndef DEFS_H_INCLUDED
#define DEFS_H_INCLUDED

#define TABLE_LEN 4
#define LINE_LEN 1024


// ALL are signed Chars:
#define TOKEN_TYPE_CHAR_STR 20
#define TOKEN_TYPE_STR_CONST 21
#define TOKEN_TYPE_NUMBER 22

#define TOKEN_TYPE_OPERATOR 24
#define TOKEN_TYPE_DIVIDER 25



//#define TOKEN_R_TYPE_KEY_WD 30
#define TOKEN_R_TYPE_STR_DEF 31
#define TOKEN_R_TYPE_FUNC 32
// #define TOKEN_R_TYPE_EX_VAR 33 //not in expressions
#define TOKEN_R_TYPE_EX_FUNC 34 //not in expressions
#define TOKEN_R_TYPE_NEW_ID 35

#define TOKEN_R_TYPE_VALUE 38// in expressions
#define TOKEN_R_TYPE_CONST 39
#define TOKEN_R_TYPE_VARIABLE 40


#define TOKEN_R_OP_EQUAL_TO 70
#define TOKEN_R_OP_G_T 71
#define TOKEN_R_OP_L_T 72
#define TOKEN_R_OP_EQ_GT 73
#define TOKEN_R_OP_PLUS 74
#define TOKEN_R_OP_MINUS 75
#define TOKEN_R_OP_MULTI_B 76
#define TOKEN_R_OP_DIVD_B 77
#define TOKEN_R_OP_INTEG_DIV 78
#define TOKEN_R_OP_REMAIN_DIV 79
#define TOKEN_R_OP_STR_CONNECT 80

#define TOKEN_R_ASSIGN 85

#define TOKEN_R_DIV_L_SBRA 90
#define TOKEN_R_DIV_R_SBRA 91
#define TOKEN_R_DIV_COMMA 92

#define TOKEN_R_KEYWD_IF 100
#define TOKEN_R_KEYWD_ELSE 101
#define TOKEN_R_KEYWD_ELIF 112
#define TOKEN_R_KEYWD_WHILE 102
#define TOKEN_R_KEYWD_FOR 103
#define TOKEN_R_KEYWD_DEF 104
#define TOKEN_R_KEYWD_FUNCTION 105
#define TOKEN_R_KEYWD_END 106 //
#define TOKEN_R_KEYWD_VAR 107
#define TOKEN_R_KEYWD_GLOBAL 108
#define TOKEN_R_KEYWD_FROM 109
#define TOKEN_R_KEYWD_TO 110
#define TOKEN_R_KEYWD_RETURN 111
#define TOKEN_R_KEYWD_ASSIGN 113
#define TOKEN_R_KEYWD_BREAK 114

#define VAL_TYPE_INT 40
#define VAL_TYPE_FLOAT 41 // double
#define VAL_TYPE_L_FLOAT 42 //long double
#define VAL_TYPE_TABLE 43
#define VAL_TYPE_ARRAY 44
#define VAL_TYPE_STRING 45
#define VAL_TYPE_COMPLEX 46

#define VAL_TYPE_NULL 50
#define VAL_TYPE_NOT_A_N 51
#define VAL_TYPE_INFINITE 52

#define V_ARRAY_DIST_DIST_CASE_N_S 61
#define V_ARRAY_DIST_DIST_CASE_S 62
#define V_ARRAY_DIST_N_DIST_CASE_S 63
#define V_ARRAY_DIST_N_DIST_N_CASE_S 64

//comma is left divider and right divider

#define LIM_INT_MIN (-2147483647L) //(-2147483648L)
#define LIM_INT_MAX 2147483647L
#define LIM_LL_INT_MIN (-9223372036854775808)
#define LIM_LL_INT_MAX 9223372036854775807

#define TREE_NODE_OP_PLUS //add / and / be added to
#define TREE_NODE_OP_MINUS
#define TREE_NODE_OP_MULIPLED_BY //times
#define TREE_NODE_OP_DIVIDED_BY //
#define TREE_NODE_OP_POWER
#define TREE_NODE_OP_SQRT


#define SENTENCE_TYPE_UNRECOGNIZED 10
#define SENTENCE_TYPE_IF_0_JUMP 11
#define SENTENCE_TYPE_IF_1_JUMP 16
#define SENTENCE_TYPE_FORCE_JUMP 12
#define SENTENCE_TYPE_NORMAL 13
#define SENTENCE_TYPE_FUNC_DEF 14
#define SENTENCE_TYPE_ACQUIRE 15


#endif // DEFS_H_INCLUDED
